Repository dotnet/corefxlab, pull requests merged in 2018-06, with the labels that each got.

#2329 Optimize JsonWriterUtf8 and JsonWriterUtf16 WriteNull() methods (#2315)
  src/System.Text.JsonLab/System/Text/Json/JsonConstants.cs
  src/System.Text.JsonLab/System/Text/Json/JsonWriterUtf16.cs
  src/System.Text.JsonLab/System/Text/Json/JsonWriterUtf8.cs
  tests/System.Text.JsonLab.Tests/JsonWriterTests.cs
Labels: Hackathon, area-System.Text.Json

#2330 Use Utf8Parser to unescape percent encoding
  src/System.Text.Encodings.Web.Utf8/UrlEncoder.cs
  tests/Benchmarks/System.Text.Encodings.Web.Utf8/UrlEncoderPerf.cs
  tests/System.Text.Encodings.Web.Utf8.Tests/UrlEncoderTests.cs
Labels: Hackathon

#2336 Add a benchmark for Range enumeration
  src/System.Buffers.Experimental/System/Range.cs
  tests/Benchmarks/System/RangeEnumeration.cs
Labels: Hackathon

#2342 Update Readme.md to include System.Devices.Gpio
  README.md
Labels: area-System.Devices.Gpio

#2335 Port Encoding (UTF-8/UTF-16/UTF-32) performance comparison test to BenchmarkDotNet
  tests/Benchmarks/Benchmarks.csproj
  tests/Benchmarks/System.Text.Primitives/CodePoint.cs
  tests/Benchmarks/System.Text.Primitives/EncodeFromUtf16toUtf8.cs
  tests/Benchmarks/System.Text.Primitives/EncodeFromUtf32toUtf16.cs
  tests/Benchmarks/System.Text.Primitives/EncodeFromUtf32toUtf8.cs
  tests/Benchmarks/System.Text.Primitives/EncodeFromUtf8toUtf16.cs
  tests/Benchmarks/System.Text.Primitives/UtfEncoderHelper.cs
  tests/System.Text.Primitives.Tests/Encoding/Performance/PerfTests.CoreCLR.cs
  tests/System.Text.Primitives.Tests/Encoding/Performance/PerfTests.Span.cs
Labels: Hackathon

#2349 Rename UtfEncoderHelper to EncoderHelper
  tests/Benchmarks/System.Text.Primitives/CodePoint.cs
  tests/Benchmarks/System.Text.Primitives/EncodeFromUtf16toUtf8.cs
  tests/Benchmarks/System.Text.Primitives/EncodeFromUtf32toUtf16.cs
  tests/Benchmarks/System.Text.Primitives/EncodeFromUtf32toUtf8.cs
  tests/Benchmarks/System.Text.Primitives/EncodeFromUtf8toUtf16.cs
  tests/Benchmarks/System.Text.Primitives/EncoderHelper.cs
Labels: Hackathon

#2338 Address PR feedback from #2329
  src/System.Text.JsonLab/System/Text/Json/JsonConstants.cs
  src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs
Labels: Hackathon, area-System.Text.Json

#2333 Migrate Base64 decoding benchmarks to Benchmark.DotNet
  tests/Benchmarks/Benchmarks.csproj
  tests/Benchmarks/System.Binary.Base64/Base64Encode.cs
  tests/Benchmarks/System.Binary.Base64/Stiching.cs
  tests/System.Binary.Base64.Tests/PerformanceTests.cs
Labels: Hackathon
